Qt6: Fix selectedItemsData() return type
Fixes the following warning:

    Warning: [default] QtWarning: QMetaMethod::invokeMethod: return type
    mismatch for method ScriptableProxy::selectedItemsData(): cannot
    convert from QList<QVariantMap> to QList<QMap<QString,QVariant>>
    during invocation
    ERROR: Bad scriptable proxy slot call: selectedItemsData()