itemencrypted: Remove explicit timeout for gpg encryption
There is still some builtin timeout in gpg2.

Omits printing "tab is corrupted or some plugins are missing" message if
decryption fails.

Error for the timeout:

    ERROR: ItemEncrypt ERROR: GnuPG stderr:
    ERROR:    gpg: encrypted with 2048-bit RSA key, ID ...
    ERROR:          "copyq"
    ERROR:    gpg: public key decryption failed: Timeout
    ERROR:    gpg: decryption failed: No secret key

Error for cancelling the pasword entry dialog:

    ERROR: ItemEncrypt ERROR: GnuPG stderr:
    ERROR:    gpg: encrypted with 2048-bit RSA key, ID ...
    ERROR:          "copyq"
    ERROR:    gpg: public key decryption failed: Operation cancelled
    ERROR:    gpg: decryption failed: No secret key

In both cases notification "Encryption failed" is shown.

Fixes #841